[tool.mypy]
python_version = "3.10"
exclude = "venv"
check_untyped_defs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
#disallow_any_unimported = True
ignore_missing_imports = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true

[tool.flake8]
ignore = "F401"
max-line-length = 120
exclude = [".git", "__pycache__", ".mypy_cache", "deploy", "libs", "target", "venv", ".github"]
max-complexity = 20