name: lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        pflake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        pflake8 . --count --exit-zero --statistics
    - name: Mypy check
      run: |
        mypy .

    - name: Generate OAS
      run: |
        python manage.py generate-oas -o openapi.json

    - name: Generate Swagger UI
      uses: Legion2/swagger-ui-action@v1
      with:
        output: swagger-ui
        spec-file: openapi.json

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        #github_token: ${{ secrets.GITHUB_TOKEN }}
        deploy_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        publish_branch: gh-pages
        publish_dir: swagger-ui
